### ISSUE TITLE
hello, the plugin works with sunmi v1 to print

### ISSUE THREAD

**Issue by gsusalvarado** [labibramadhan/cordova-sunmi-inner-printer#1]
How can I use this plugin, I've read that you can only print native android, can you use it with ionic, or how can I start using it? Thank you

**Comment by labibramadhan** [comment]
First, install by typing ionic `cordova plugin add https://github.com/labibramadhan/cordova-sunmi-inner-printer.git`

Then, use it on your cordova javascript codes by calling: `window. sunmiInnerPrinter.[methods available on [here](https://github.com/labibramadhan/cordova-sunmi-inner-printer/blob/master/www/innerprinter.js)]`

**Comment by gsusalvarado** [comment]
Thanks

**Comment by ayserious** [comment]
I'm trying to write a cordova program and run a plugin. Your plugin, do I need to install something else to add it?

**Comment by ayserious** [comment]
Hello, You can preview the code to run the plugin. Was it a little bit? I'm very thankful

**Comment by labibramadhan** [comment]
For more detail how to start testing, see https://github.com/labibramadhan/cordova-sunmi-inner-printer/issues/2#issuecomment-342366093

**Comment by ibatinfo** [comment]
> First, install by typing `ionic cordova plugin add https://github.com/labibramadhan/cordova-sunmi-inner-printer.git`
> 
> Then, use it on your cordova javascript codes by calling: `window.sunmiInnerPrinter.[methods available on` [here](https://github.com/labibramadhan/cordova-sunmi-inner-printer/blob/master/www/innerprinter.js)`]`

Hello, am using phonegap to convert my js, html and css app. I only have access to config.xml
The question is do I need to indicate anything in my config.xml to allow the print. And the innerprinter.js, must it be in the same location where the java file is
