### ISSUE TITLE
Hello, You can preview the code to run the plugin. Was it a little bit? I'm very thankful

### ISSUE THREAD

**Issue by ayserious** [labibramadhan/cordova-sunmi-inner-printer#2]
Hello, You can preview the code to run the plugin. Was it a little bit? I'm very thankful

I tried to use it. But nothing happened.

Example of a command I run

window.sunmiInnerPrinter.printerInit
window.sunmiInnerPrinter.printerSelfChecking

**Comment by labibramadhan** [comment]
How about this code:

`window.sunmiInnerPrinter.printOriginalText("Hello World!")`

Run inside `ondeviceready` event

**Comment by ayserious** [comment]
Oh my god, i've been trying for months now, i'm thank you so much. it work

**Comment by saberprashant** [comment]
Hey @ibatinfo @ayserious @labibramadhan , can you please tell me the whole process to get this plugin work out in my Ionic 3 app??
I already added the plugin with:
```
ionic cordova plugin add `with your url`
```

Then I try to run this command in my ```app.component.ts``` in platform.ready() event:
```
window.sunmiInnerPrinter.printOriginalText("Hello Printer!");
```
But, this is giving me error saying ```window.sunmiInnerPrinter is not available```.


Also, when I try to add this above my @Component:
```
declare let sunmiInnerPrinter: any;
```
and then using it in my platform.ready()like:
```
sunmiInnerPrinter.printOriginalText("Hello Printer!");
```
This time it doesn't give any errors, but it doesn't print anything when I build and run it in Sunmi v1 POS machine.


Please help me to make this work. 
Thanks :)
